"""empty message

Revision ID: e1edeb73499c
Revises: 
Create Date: 2017-12-23 18:28:33.258533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1edeb73499c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('manga_manga_id_uindex', table_name='manga')
    op.create_unique_constraint(None, 'manga', ['manga_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manga', type_='unique')
    op.create_index('manga_manga_id_uindex', 'manga', ['manga_id'], unique=True)
    # ### end Alembic commands ###
